version: '3.5'
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=trainerai_user
      - POSTGRES_DB=trainerai_development
      - POSTGRES_PASSWORD=trainerai_DBpassWord
      - POSTGRES_INITDB_ARGS="--username=trainerai_user"
      - DATABASE_URL=postgresql://trainerai_user:trainerai_DBpassWord@postgres:5432/trainerai?
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - POSTGRES_USER=trainerai_user
      - POSTGRES_DB=trainerai_development
      - POSTGRES_PASSWORD=trainerai_DBpassWord
      - DATABASE_URL=postgresql://trainerai_user:trainerai_DBpassWord@postgres:5432/trainerai?

volumes:
  redis:
  postgres: