default: &default
  encoding: utf8
  pool: <%= ENV.fetch("DATABASE_POOL") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  adapter: postgresql
  database: <%= ENV.fetch("DATABASE_NAME_DEV") %>
  host: <%= ENV.fetch("DATABASE_HOST_DEV") %>

test:
  <<: *default
  adapter: postgresql
  database: <%= ENV.fetch("DATABASE_NAME_TEST") %>
  host: <%= ENV.fetch("DATABASE_HOST_TEST") %>

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV.fetch("DATABASE_NAME_PROD") %>
  host: <%= ENV.fetch("DATABASE_HOST_PROD") %>
